- name: SA-8 Change default umask
  replace:
    dest=/etc/profile
    regexp='umask [0-7]*$'
    replace='umask 077'
  tags:
  - conf-low
  - conf-medium
  - conf-high
  - int-low
  - int-medium
  - int-high
  - avail-low
  - avail-medium
  - avail-high

- name: SA-8 Change default bash umask
  replace:
    dest=/etc/bashrc
    regexp='umask [0-7]*$'
    replace='umask 077'
  tags:
  - conf-low
  - conf-medium
  - conf-high
  - int-low
  - int-medium
  - int-high
  - avail-low
  - avail-medium
  - avail-high

- name: SA-8 Change cshell umask
  replace:
    dest=/etc/csh.cshrc
    regexp='umask [0-7]*$'
    replace='umask 077'
  tags:
  - conf-low
  - conf-medium
  - conf-high
  - int-low
  - int-medium
  - int-high
  - avail-low
  - avail-medium
  - avail-high

- name: SA-8 Set SSH Idle Timeout Interval
  lineinfile: dest=/etc/ssh/sshd_config regexp=".*ClientAliveInterval.*" line="ClientAliveInterval 900"
  tags:
  - conf-low
  - conf-medium
  - conf-high
  - int-low
  - int-medium
  - int-high
  - avail-low
  - avail-medium
  - avail-high

- name: SA-8 Set SSH Maximum Number of Client Connections
  lineinfile: dest=/etc/ssh/sshd_config regexp=".*ClientAliveCountMax.*" line="ClientAliveCountMax 0"
  tags:
  - conf-low
  - conf-medium
  - conf-high
  - int-low
  - int-medium
  - int-high
  - avail-low
  - avail-medium
  - avail-high
