---
- import_tasks: kernel_parameters_which_affect_networking.yml
- import_tasks: wireless_networking.yml
- import_tasks: ipv6.yml
- import_tasks: iptables_and_ip6_tables.yml
- import_tasks: firewalld.yml
- import_tasks: uncommon_network_protocols.yml
- import_tasks: ipsec_support.yml
